In [2]:
import numpy as np
 
A = np.array([ [3, 1, 5], [9, 8, -1], [10, 12, 2] ])
B = np.array([ [8, -1, 8], [2, 1, 3], [18, 2, 32] ])
 
C= A + B
print("A : ", A)
print("B : ", B)
print("A + B : ", C)

A :  [[ 3  1  5]
 [ 9  8 -1]
 [10 12  2]]
B :  [[ 8 -1  8]
 [ 2  1  3]
 [18  2 32]]
A + B :  [[11  0 13]
 [11  9  2]
 [28 14 34]]


In [3]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
       result[i][j] = X[i][j] + Y[i][j]

for r in result:
   print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


In [4]:
#Ex2
import numpy as np
 
A = np.array([ [3, 1, 5], [9, 8, -1], [24, 12, 2] ])
B = np.array([ [8, -1, 9], [2, 1, 3], [20, 2, 32] ])
 
C = A.dot(B)
 
print("A : ", A)
print("B : ", B)
print("A * B : ", C)

A :  [[ 3  1  5]
 [ 9  8 -1]
 [24 12  2]]
B :  [[ 8 -1  9]
 [ 2  1  3]
 [20  2 32]]
A * B :  [[126   8 190]
 [ 68  -3  73]
 [256  -8 316]]


In [6]:
#Ex3
def eststochastique(P):
    nl = len(P)  # nombre de lignes
    nc = len(P[0])  # nombre de colonnes
 
    etat = True  # on suppose que la matrice est stochastique
    for i in range(nl):
        s = 0
        for j in range(nc):
            s += P[i][j]
        if s > 1:
            etat = False
            break
    return etat
 
 
def estbistochastique(P):
    nl = len(P)  # nombre de lignes
    nc = len(P[0])  # nombre de colonnes
 
    etat = True  # on suppose que la matrice est bistochastique
    if(eststochastique(P)):
        for j in range(nc):
            s = 0
            for i in range(nl):
                s += P[i][j]
            if s > 1:
                etat = False
                break
    return etat
 
 
def vecteurstable(G, h):
    nl = len(G)  # nombre de lignes
    nc = len(G[0])  # nombre de colonnes
    etat = True
    if(eststochastique(G)):
        for j in range(nc):
            s = 0
            for i in range(nl):
                s += h[i]*G[i][j]
            if s != h[j]:
                etat = False
                break
    else:
        etat = False

In [7]:
import numpy as np
 
A = np.array([ [3, 1, 5], [9, 8, -1], [18, 12, 2] ])
 
C = A.transpose()
 
print("A : ", A)
print("Transposée de A : ", C)

A :  [[ 3  1  5]
 [ 9  8 -1]
 [18 12  2]]
Transposée de A :  [[ 3  9 18]
 [ 1  8 12]
 [ 5 -1  2]]


In [8]:
#Ex5
# appliquer une permutation
def apply_permutation(A,perm,N):
    B=np.empty_like(A) # A est une matrice NxN d'entiers dans range(N)
    for i in range(N):
            B[A[:]==i]=perm[i] # perm est une permutation de range(N)
    return B